// --- КОНСТАНТИ ---
export const BAUD_RATE = 38400;
export const DEFAULT_PAGE = 'pages/terminal.html';

// --- СЛОВНИК ПЕРЕКЛАДІВ (ЧИСТИЙ ТЕКСТ БЕЗ ЕМОДЗІ) ---
export const translations = {
    'uk': {
        'menu_title': 'CAN Монітор',
        'menu_inverter': 'Інвертор',
        'menu_bms': 'БМС',
        'menu_ecu': 'ECU',

        'menu_bms_params': 'Параметри',
        'menu_bms_cells': 'Комірки',
        'menu_bms_temp_map': 'T-Мапа',
        'menu_bms_soc_map': 'SOC-Мапа',

        'menu_internal': 'Внутрішні',
        'menu_settings': 'Налаштування',
        'menu_update': 'Оновлення',

        'menu_terminal': 'Термінал',

        'status_adapter': 'Адаптер',
        'status_can': 'Шина (CAN)',
        'btn_connect': 'Підключити',
        'btn_write': 'Запис',
        'btn_on': 'УВІМК',
        'btn_off': 'ВИМК',
        'col_read': 'Поточне значення',
        'col_write': 'Нове значення',
        'placeholder_new_value': 'Значення...',

        // Terminal
        'terminal_title': 'Термінал (Debug)',
        'terminal_subtitle': 'Сирий потік даних з адаптера для дебагу:',
        'terminal_input_placeholder': 'Введіть команду (напр. ATZ)...',
        'terminal_send_button': 'Надіслати',

        // Inverter
        'inverter_title': 'Інвертор',
        'inv_hv_voltage': 'Висока напруга інвертора',
        'inv_temp': 'Температура інвертора',
        'inv_motor_temp': 'Температура мотора',
        'inv_selector': 'Позиція селектора',
        'inv_rpm': 'Оберти мотора',
        'inv_pedal': 'Позиція педалі',
        'inv_torque_req': 'Запит моменту',
        'inv_ready': 'Готовність',
        'inv_error': 'Помилка інвертора',
        'inv_status': 'Статус',
        'inv_max_torque': 'Максимальний момент',
        'inv_pedal_min': 'Мінімальна позиція педалі',
        'inv_pedal_max': 'Максимальна позиція педалі',
        'inv_torque_cal': 'Момент у точці калібрування',
        'inv_pedal_cal': 'Позиція педалі у точці калібрування',
        'inv_not_pressed': 'Позиція не натиснутої педалі',
        'inv_torque_not_pressed': 'Момент при не натиснутій педалі',

        // BMS Parameters
        'bms_title': 'Параметри BMS:',
        'bms_battery_voltage': 'Напруга батареї',
        'bms_cell_min': 'Мінімальна напруга комірки',
        'bms_cell_max': 'Максимальна напруга комірки',
        'bms_balancing': 'Балансування',
        'bms_recuperation': 'Рекуперація',
        'bms_cut_charge': 'Відключити заряд при завершенні',
        'bms_cell_off_charging': 'Напруга комірки відключення заряду',
        'bms_cell_start_balancing': 'Напруга комірки початку балансування',
        'bms_cell_on_tortle': 'Напруга комірки обмеження потужності',
        'bms_cell_off_battery': 'Напруга комірки відключення батареї',
        'bms_soc': 'SOC',
        'bms_soc_ah': 'SOC в Ампер-годинах',
        'bms_soh_ah': 'SOH в Ампер-годинах',
        'bms_current': 'Струм',
        'bms_current_sens_type': 'Тип датчика струму',
        'bms_current_sens1': 'Датчик струму 1',
        'bms_current_sens2': 'Датчик струму 2',
        'bms_ir_sens': 'Напруга ІЧ датчика',
        'bms_min_cell_num': 'Номер комірки MIN',
        'bms_max_cell_num': 'Номер комірки MAX',
        'bms_sens_leaf': 'Leaf',
        'bms_sens_off': 'ВИМК',
        'bms_sens_volt1': 'Volt 1',

        // Settings
        'settings_title': 'Налаштування ECU',
        'set_wheel_circ': 'Окружність колеса',
        'set_contactor_voltage': 'Напруга вмикання контактора',
        'set_type_selector': 'Тип селектора',
        'set_type_start_btn': 'Тип кнопки старт',
        'set_type_invertor': 'Тип інвертора',
        'set_pump_temp': 'Температура вмикання помпи',
        'set_fan_high_temp': 'Температура вмикання вентилятора (швидка)',
        'set_fan_low_temp': 'Температура вмикання вентилятора (повільна)',
        'set_type_bms': 'Тип BMS',
        'opt_button': 'Кнопка',
        'opt_leaf': 'Leaf',
        'opt_psa': 'PSA',
        'opt_with_fixation': 'З фіксацією',
        'opt_without_fixation': 'Без фіксації',
        'opt_aze0': 'AZE0',
        'opt_ze0': 'ZE0',
        'opt_ze1': 'ZE1',
        'opt_off': 'ВИМК',
        'opt_volt_gen1': 'Volt Gen 1',
        'opt_orion2': 'Orion 2',
        'opt_vw_id': 'VW ID',

        // Internal Monitor
        'internal_title': 'Внутрішній монітор',
        'int_analog_inputs': 'Аналогові входи (АЦП)',
        'int_digital_outputs': 'Цифрові виходи та статус',
        'int_12v_adc': '12V АЦП',
        'int_5v_adc': '5V АЦП',
        'int_a1_adc': 'A1 АЦП',
        'int_a2_adc': 'A2 АЦП',
        'int_a4_adc': 'A4 АЦП',
        'int_a5_pedal': 'A5 АЦП (Педаль 1)',
        'int_a7_adc': 'A7 АЦП',
        'int_a8_adc': 'A8 АЦП',
        'int_a9_brake': 'A9 АЦП (Датчик гальма)',
        'int_a3_chademo': 'A3 (Chademo IN0)',
        'int_d5': 'D5',
        'int_d6_brake': 'D6 (Стоп-сигнал)',
        'int_d7_chademo': 'D7 (Chademo IN1)',
        'int_d46_chademo': 'D46 (Chademo IN2)',
        'int_d48': 'D48',
        'int_d50': 'D50',
        'int_d52': 'D52',
        'int_device_id': 'ID пристрою',
        'int_soft_ver': 'Версія ПЗ',
        'int_contactor_plus': 'A10 (Контактор +)',
        'int_contactor_minus': 'A11 (Контактор -)',
        'int_precharge': 'D11 (Попередній заряд)',
        'int_water_pump': 'D24 (Водяна помпа)',
        'int_fan_high': 'D9 (Вентилятор швидкий)',
        'int_fan_low': 'D26 (Вентилятор повільний)',
        'int_brake_booster': 'D25 (Вакуумна помпа гальм)',
        'int_dac1_brake': 'DAC1 (Стоп-сигнал)',
        'int_d8_chademo': 'D8 (Chademo out0)',
        'int_d12_chademo': 'D12 (Chademo out1)',
        'int_can3': 'Статус CAN 3',
        'int_test_output': 'Тестування виходу',
        'int_test_button': 'Тест',

        // Update
        'update_title': 'Оновлення прошивки пристрою',
        'update_overlay_title': 'Йде оновлення прошивки...',
        'update_overlay_text1': 'Будь ласка, не закривайте і не оновлюйте цю сторінку!',
        'update_overlay_text2': 'Це може пошкодити ваш пристрій.',
        'update_file_select': 'Натисніть, щоб обрати файл',
        'update_file_not_selected': 'Файл не обрано',
        'update_upload_button': 'Залити прошивку',
        'update_status_waiting': 'Очікування...',
        'update_status_reading': 'Читання файлу...',
        'update_status_starting': 'Початок оновлення...',
        'update_status_success': 'Оновлення завершено успішно!',
        'update_status_error': 'Помилка оновлення!',
        'update_alert_no_file': 'Будь ласка, оберіть файл прошивки!',
        'update_alert_no_adapter': 'Будь ласка, підключіть адаптер перед оновленням!',
        'update_confirm_title': 'ПОПЕРЕДЖЕННЯ!',
        'update_confirm_text': 'Ви збираєтесь оновити прошивку пристрою.\nПід час оновлення НЕ ВІДКЛЮЧАЙТЕ адаптер та НЕ ЗАКРИВАЙТЕ сторінку!',
        'update_confirm_file': 'Файл',
        'update_confirm_size': 'Розмір',
        'update_confirm_bytes': 'байт',
        'update_confirm_continue': 'Продовжити?',
        'update_alert_success': 'Прошивка успішно завантажена!\nПристрій буде перезавантажено.',
        'update_alert_error': 'Помилка оновлення прошивки!\nПеревірте з\'єднання та спробуйте ще раз.',
        'update_alert_critical': 'Критична помилка',

        // BMS SOC Map
        'bms_soc_map_description': 'Тут буде візуалізація заряду (SOC) по комірках.',
        'soc_calibration_table': 'Таблиця калібрування SOC',
        'soc_write_values': 'Запис значень SOC',
        'soc_calibration_mode': 'Калібрування SOC по напрузі комірки',
        'soc_0': 'SOC 0%',
        'soc_10': 'SOC 10%',
        'soc_20': 'SOC 20%',
        'soc_30': 'SOC 30%',
        'soc_40': 'SOC 40%',
        'soc_50': 'SOC 50%',
        'soc_60': 'SOC 60%',
        'soc_70': 'SOC 70%',
        'soc_80': 'SOC 80%',
        'soc_90': 'SOC 90%',
        'soc_100': 'SOC 100%',
        'soc_write_mode': 'Запис режиму калібрування',
        'soc_write_0': 'Записати SOC 0%',
        'soc_write_10': 'Записати SOC 10%',
        'soc_write_20': 'Записати SOC 20%',
        'soc_write_30': 'Записати SOC 30%',
        'soc_write_40': 'Записати SOC 40%',
        'soc_write_50': 'Записати SOC 50%',
        'soc_write_60': 'Записати SOC 60%',
        'soc_write_70': 'Записати SOC 70%',
        'soc_write_80': 'Записати SOC 80%',
        'soc_write_90': 'Записати SOC 90%',
        'soc_write_100': 'Записати SOC 100%',
        'soc_write_btn': 'Записати',
    },
    'en': {
        'menu_title': 'CAN Monitor',
        'menu_inverter': 'Inverter',
        'menu_bms': 'BMS',
        'menu_ecu': 'ECU',

        'menu_bms_params': 'Parameters',
        'menu_bms_cells': 'Cells',
        'menu_bms_temp_map': 'Temp Map',
        'menu_bms_soc_map': 'SOC Map',

        'menu_internal': 'Internal',
        'menu_settings': 'Settings',
        'menu_update': 'Update',

        'menu_terminal': 'Terminal',

        'status_adapter': 'Adapter',
        'status_can': 'CAN Bus',
        'btn_connect': 'Connect',
        'btn_write': 'Write',
        'btn_on': 'ON',
        'btn_off': 'OFF',
        'col_read': 'Current Value',
        'col_write': 'New Value',
        'placeholder_new_value': 'Value...',

        // Terminal
        'terminal_title': 'Terminal (Debug)',
        'terminal_subtitle': 'Raw data stream from adapter for debugging:',
        'terminal_input_placeholder': 'Enter command (e.g. ATZ)...',
        'terminal_send_button': 'Send',

        // Inverter
        'inverter_title': 'Inverter',
        'inv_hv_voltage': 'Inverter high voltage',
        'inv_temp': 'Inverter temperature',
        'inv_motor_temp': 'Motor temperature',
        'inv_selector': 'Selector position',
        'inv_rpm': 'Motor RPM',
        'inv_pedal': 'Pedal position',
        'inv_torque_req': 'Torque request',
        'inv_ready': 'Ready',
        'inv_error': 'Inverter error',
        'inv_status': 'Status',
        'inv_max_torque': 'Max torque',
        'inv_pedal_min': 'Pedal MIN position',
        'inv_pedal_max': 'Pedal MAX position',
        'inv_torque_cal': 'Torque in calibration point',
        'inv_pedal_cal': 'Pedal position in calibration point',
        'inv_not_pressed': 'Not pressed pedal position',
        'inv_torque_not_pressed': 'Torque while pedal not pressed',

        // BMS Parameters
        'bms_title': 'BMS Parameters:',
        'bms_battery_voltage': 'Battery voltage',
        'bms_cell_min': 'Cell MIN voltage',
        'bms_cell_max': 'Cell MAX voltage',
        'bms_balancing': 'Balancing',
        'bms_recuperation': 'Recuperation',
        'bms_cut_charge': 'Cut charge power when finishing',
        'bms_cell_off_charging': 'Cell voltage off charging',
        'bms_cell_start_balancing': 'Cell voltage start balancing',
        'bms_cell_on_tortle': 'Cell voltage on tortle',
        'bms_cell_off_battery': 'Cell voltage off battery',
        'bms_soc': 'SOC',
        'bms_soc_ah': 'SOC in Ah',
        'bms_soh_ah': 'SOH in Ah',
        'bms_current': 'Current',
        'bms_current_sens_type': 'Current sens type',
        'bms_current_sens1': 'Current sens 1',
        'bms_current_sens2': 'Current sens 2',
        'bms_ir_sens': 'IR sens voltage',
        'bms_min_cell_num': 'MIN Cell number',
        'bms_max_cell_num': 'MAX Cell number',
        'bms_sens_leaf': 'Leaf',
        'bms_sens_off': 'OFF',
        'bms_sens_volt1': 'Volt 1',

        // Settings
        'settings_title': 'ECU settings',
        'set_wheel_circ': 'Wheel circumference',
        'set_contactor_voltage': 'Contactor ON voltage',
        'set_type_selector': 'Type selector',
        'set_type_start_btn': 'Type start button',
        'set_type_invertor': 'Type inverter',
        'set_pump_temp': 'Pump start temperature',
        'set_fan_high_temp': 'Temp fan ON high speed',
        'set_fan_low_temp': 'Temp fan ON low speed',
        'set_type_bms': 'Type BMS',
        'opt_button': 'Button',
        'opt_leaf': 'Leaf',
        'opt_psa': 'PSA',
        'opt_with_fixation': 'With fixation',
        'opt_without_fixation': 'Without fixation',
        'opt_aze0': 'AZE0',
        'opt_ze0': 'ZE0',
        'opt_ze1': 'ZE1',
        'opt_off': 'OFF',
        'opt_volt_gen1': 'Volt Gen 1',
        'opt_orion2': 'Orion 2',
        'opt_vw_id': 'VW ID',

        // Internal Monitor
        'internal_title': 'Internal Monitor',
        'int_analog_inputs': 'Analog Inputs (ADC)',
        'int_digital_outputs': 'Digital Outputs & Status',
        'int_12v_adc': '12v ADC',
        'int_5v_adc': '5v ADC',
        'int_a1_adc': 'A1 ADC',
        'int_a2_adc': 'A2 ADC',
        'int_a4_adc': 'A4 ADC',
        'int_a5_pedal': 'A5 ADC (Pedal 1)',
        'int_a7_adc': 'A7 ADC',
        'int_a8_adc': 'A8 ADC',
        'int_a9_brake': 'A9 ADC (Brake sens)',
        'int_a3_chademo': 'A3 (Chademo IN0)',
        'int_d5': 'D5',
        'int_d6_brake': 'D6 (Brake light)',
        'int_d7_chademo': 'D7 (Chademo IN1)',
        'int_d46_chademo': 'D46 (Chademo IN2)',
        'int_d48': 'D48',
        'int_d50': 'D50',
        'int_d52': 'D52',
        'int_device_id': 'Device ID',
        'int_soft_ver': 'Soft ver',
        'int_contactor_plus': 'A10 (Contactor +)',
        'int_contactor_minus': 'A11 (Contactor -)',
        'int_precharge': 'D11 (Precharge)',
        'int_water_pump': 'D24 (Water pump)',
        'int_fan_high': 'D9 (Fan high speed)',
        'int_fan_low': 'D26 (Fan low speed)',
        'int_brake_booster': 'D25 (Brake booster)',
        'int_dac1_brake': 'DAC1 (Brake light)',
        'int_d8_chademo': 'D8 (Chademo out0)',
        'int_d12_chademo': 'D12 (Chademo out1)',
        'int_can3': 'CAN 3 Status',
        'int_test_output': 'Test output',
        'int_test_button': 'Test',

        // Update
        'update_title': 'Device Firmware Update',
        'update_overlay_title': 'Firmware update in progress...',
        'update_overlay_text1': 'Please do not close or refresh this page!',
        'update_overlay_text2': 'This may damage your device.',
        'update_file_select': 'Click to select file',
        'update_file_not_selected': 'No file selected',
        'update_upload_button': 'Upload Firmware',
        'update_status_waiting': 'Waiting...',
        'update_status_reading': 'Reading file...',
        'update_status_starting': 'Starting update...',
        'update_status_success': 'Update completed successfully!',
        'update_status_error': 'Update error!',
        'update_alert_no_file': 'Please select a firmware file!',
        'update_alert_no_adapter': 'Please connect adapter before updating!',
        'update_confirm_title': 'WARNING!',
        'update_confirm_text': 'You are about to update the device firmware.\nDuring the update, DO NOT DISCONNECT the adapter and DO NOT CLOSE the page!',
        'update_confirm_file': 'File',
        'update_confirm_size': 'Size',
        'update_confirm_bytes': 'bytes',
        'update_confirm_continue': 'Continue?',
        'update_alert_success': 'Firmware uploaded successfully!\nThe device will be rebooted.',
        'update_alert_error': 'Firmware update error!\nCheck the connection and try again.',
        'update_alert_critical': 'Critical error',

        // BMS SOC Map
        'bms_soc_map_description': 'SOC (State of Charge) visualization by cells will be here.',
        'soc_calibration_table': 'SOC Calibration Table',
        'soc_write_values': 'Write SOC Values',
        'soc_calibration_mode': 'SOC Calibration by Cell Voltage',
        'soc_0': 'SOC 0%',
        'soc_10': 'SOC 10%',
        'soc_20': 'SOC 20%',
        'soc_30': 'SOC 30%',
        'soc_40': 'SOC 40%',
        'soc_50': 'SOC 50%',
        'soc_60': 'SOC 60%',
        'soc_70': 'SOC 70%',
        'soc_80': 'SOC 80%',
        'soc_90': 'SOC 90%',
        'soc_100': 'SOC 100%',
        'soc_write_mode': 'Write Calibration Mode',
        'soc_write_0': 'Write SOC 0%',
        'soc_write_10': 'Write SOC 10%',
        'soc_write_20': 'Write SOC 20%',
        'soc_write_30': 'Write SOC 30%',
        'soc_write_40': 'Write SOC 40%',
        'soc_write_50': 'Write SOC 50%',
        'soc_write_60': 'Write SOC 60%',
        'soc_write_70': 'Write SOC 70%',
        'soc_write_80': 'Write SOC 80%',
        'soc_write_90': 'Write SOC 90%',
        'soc_write_100': 'Write SOC 100%',
        'soc_write_btn': 'Write',
    }
};

// --- ІКОНКИ (SVG КОДИ) ---
const icons = {
    // --- ПІДМЕНЮ ---
    list: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></svg>`,
    
    battery: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="6" width="20" height="12" rx="2" ry="2"></rect><line x1="23" y1="11" x2="23" y2="13"></line><rect x="5" y="9" width="3" height="6" fill="currentColor" stroke="none"></rect><rect x="10" y="9" width="3" height="6" fill="currentColor" stroke="none"></rect><rect x="15" y="9" width="3" height="6" fill="currentColor" stroke="none"></rect></svg>`,
    
    thermometer: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M14 14.76V3.5a2.5 2.5 0 0 0-5 0v11.26a4.5 4.5 0 1 0 5 0z"></path></svg>`,
    
    chart: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M18 20V10"></path><path d="M12 20V4"></path><path d="M6 20v-6"></path></svg>`,
    
    settings: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.1a2 2 0 0 1-1-1.72v-.51a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"></path><circle cx="12" cy="12" r="3"></circle></svg>`,
    
    chip: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><rect x="9" y="9" width="6" height="6"></rect><line x1="9" y1="1" x2="9" y2="4"></line><line x1="15" y1="1" x2="15" y2="4"></line><line x1="9" y1="20" x2="9" y2="23"></line><line x1="15" y1="20" x2="15" y2="23"></line><line x1="20" y1="9" x2="23" y2="9"></line><line x1="20" y1="14" x2="23" y2="14"></line><line x1="1" y1="9" x2="4" y2="9"></line><line x1="1" y1="14" x2="4" y2="14"></line></svg>`,
    
    upload: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>`,

    // --- ГОЛОВНЕ МЕНЮ (ДЛЯ ВИКОРИСТАННЯ В HTML) ---
    inverter: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>`,
    
    terminal: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><polyline points="4 17 10 11 4 5"></polyline><line x1="12" y1="19" x2="20" y2="19"></line></svg>`,

    // --- МОВИ ---
    lang_ua: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><text x="50%" y="55%" dominant-baseline="middle" text-anchor="middle" font-size="10" font-weight="bold">UA</text><rect x="2" y="4" width="20" height="16" rx="2" stroke-width="2"/></svg>`,
    lang_en: `<svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><text x="50%" y="55%" dominant-baseline="middle" text-anchor="middle" font-size="10" font-weight="bold">EN</text><rect x="2" y="4" width="20" height="16" rx="2" stroke-width="2"/></svg>`
};

// --- КОНФІГУРАЦІЯ МЕНЮ ---
export const menuConfig = {
    // Розділ BMS
    bms: {
        type: 'submenu', 
        defaultPage: 'pages/bms_params.html', 
        items: [
            { label: 'Параметри', link: 'pages/bms_params.html', langKey: 'menu_bms_params', icon: icons.list },
            { label: 'Комірки', link: 'pages/bms_cells.html', langKey: 'menu_bms_cells', icon: icons.battery },
            { label: 'T-Мапа', link: 'pages/bms_temp_map.html', langKey: 'menu_bms_temp_map', icon: icons.thermometer },
            { label: 'SOC-Мапа', link: 'pages/bms_soc_map.html', langKey: 'menu_bms_soc_map', icon: icons.chart }
        ]
    },

    // Розділ ECU (колишні Налаштування)
    ecu: {
        type: 'submenu',
        defaultPage: 'pages/settings.html',
        items: [
            { label: 'Налаштування', link: 'pages/settings.html', langKey: 'menu_settings', icon: icons.settings },
            { label: 'Внутрішні', link: 'pages/internal.html', langKey: 'menu_internal', icon: icons.chip },
            { label: 'Оновлення', link: 'pages/update.html', langKey: 'menu_update', icon: icons.upload }
        ]
    },

    // Прості розділи
    inverter: { type: 'direct', link: 'pages/inverter.html' },
    terminal: { type: 'direct', link: 'pages/terminal.html' }
};