// --- КОНСТАНТИ ---
export const BAUD_RATE = 38400;
export const DEFAULT_PAGE = 'pages/terminal.html';

// --- СЛОВНИК ПЕРЕКЛАДІВ ---
// (Взято з вашого файлу)
export const translations = {
    'uk': {
        'menu_title': 'CAN Монітор',
        'menu_inverter': '⚡️ Інвертор',
        'menu_bms': '🔋 БМС',
        'menu_bms_params': 'Параметри',
        'menu_bms_cells': 'Комірки',
        'menu_bms_temp_map': 'T-Мапа',
        'menu_bms_soc_map': 'SOC-Мапа',
        'menu_settings': '⚙️ Налаштування',
        'menu_update': '⬆️ Оновлення',
        'menu_terminal': '💻 Термінал',
        'status_adapter': 'Адаптер',
        'status_can': 'Шина (CAN)',
        'btn_connect': 'Підключити',
        'btn_write': 'Запис',
        'btn_on': 'УВІМК',
        'btn_off': 'ВИМК',
        'placeholder_new_value': 'Нове значення',
        'terminal_title': 'Термінал (Debug)',
        'terminal_subtitle': 'Сирий потік даних з адаптера для дебагу:',
        'inverter_title': 'Інвертор',
        // ... (тут мають бути всі ключі для інвертора) ...
        'bms_title': 'Параметри BMS:',
        'bms_battery_voltage': 'Напруга батареї',
        'bms_cell_min': 'Cell MIN напруга',
        'bms_cell_max': 'Cell MAX напруга',
        'bms_balancing': 'Балансування',
        'bms_recuperation': 'Рекуперація',
        'bms_cut_charge': 'Відсічка заряду',
        'bms_cell_off_charging': 'Напруга відкл. заряду',
        'bms_cell_start_balancing': 'Напруга старту баланс.',
        'bms_cell_on_tortle': 'Напруга "черепахи"',
        'bms_cell_off_battery': 'Напруга відкл. батареї',
        'bms_soc': 'SOC',
        'bms_soc_ah': 'SOC в Ah',
        'bms_soh_ah': 'SOH в Ah',
        'bms_current': 'Струм',
        'bms_current_sens_type': 'Тип датчика струму',
        'bms_current_sens1': 'Датчик струму 1',
        'bms_current_sens2': 'Датчик струму 2',
        'bms_ir_sens': 'IR sens напруга',
        'bms_min_cell_num': 'MIN номер комірки',
        'bms_max_cell_num': 'MAX номер комірки',
        'bms_sens_leaf': 'Leaf',
        'bms_sens_off': 'ВИМК',
        'bms_sens_volt1': 'Volt 1',
    },
    'en': {
        'menu_title': 'CAN Monitor',
        'menu_inverter': '⚡️ Inverter',
        'menu_bms': '🔋 BMS',
        'menu_bms_params': 'Parameters',
        'menu_bms_cells': 'Cells',
        'menu_bms_temp_map': 'T-Map',
        'menu_bms_soc_map': 'SOC-Map',
        'menu_settings': '⚙️ Settings',
        'menu_update': '⬆️ Update',
        'menu_terminal': '💻 Terminal',
        'status_adapter': 'Adapter',
        'status_can': 'CAN Bus',
        'btn_connect': 'Connect',
        'btn_write': 'Write',
        'btn_on': 'ON',
        'btn_off': 'OFF',
        'placeholder_new_value': 'New Value',
        'terminal_title': 'Terminal (Debug)',
        'terminal_subtitle': 'Raw data stream from adapter for debugging:',
        'inverter_title': 'Inverter',
        // ... (тут мають бути всі ключі для інвертора англійською) ...
        'bms_title': 'BMS Parameters:',
        'bms_battery_voltage': 'Battery voltage',
        'bms_cell_min': 'Cell MIN voltage',
        'bms_cell_max': 'Cell MAX voltage',
        'bms_balancing': 'Balancing',
        'bms_recuperation': 'Recuperation',
        'bms_cut_charge': 'Cut charge power when finishing',
        'bms_cell_off_charging': 'Cell voltage off charging',
        'bms_cell_start_balancing': 'Cell voltage start balancing',
        'bms_cell_on_tortle': 'Cell voltage on tortle',
        'bms_cell_off_battery': 'Cell voltage off battery',
        'bms_soc': 'SOC',
        'bms_soc_ah': 'SOC in Ah',
        'bms_soh_ah': 'SOH in Ah',
        'bms_current': 'Current',
        'bms_current_sens_type': 'Current sens type',
        'bms_current_sens1': 'Current sens 1',
        'bms_current_sens2': 'Current sens 2',
        'bms_ir_sens': 'IR sens voltage',
        'bms_min_cell_num': 'MIN Cell number',
        'bms_max_cell_num': 'MAX Cell number',
        'bms_sens_leaf': 'Leaf',
        'bms_sens_off': 'OFF',
        'bms_sens_volt1': 'Volt 1',
    }
};

